name: Verify

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python "3.10"
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: |
        git clone https://github.com/catkira/cocotb.git
        cd cocotb
        pip3 install -e .
        cd ..
        pip3 install -r requirements.txt
        sudo apt install -y --no-install-recommends iverilog
    - name: Verify with cocotb & icarus
      run: |
        pytest -v --workers=16 tests/test_dds.py
